# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpm < Formula
  desc "Claude Profile Manager — manage multiple Claude Code accounts"
  homepage "https://github.com/jakubkontra/claude-profile-manager"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JakubKontra/claude-profile-manager/releases/download/v0.2.0/cpm_darwin_amd64"
      sha256 "c502263a0c75a9a6b2a28f2a16985e00677bb2e155f693d7b8ddd381a335f1b8"

      define_method(:install) do
        bin.install "cpm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JakubKontra/claude-profile-manager/releases/download/v0.2.0/cpm_darwin_arm64"
      sha256 "4904032082b1087d16c195b5cb53c34ed7a49ae52f99299b7d6ad30743eab64e"

      define_method(:install) do
        bin.install "cpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakubKontra/claude-profile-manager/releases/download/v0.2.0/cpm_linux_amd64"
      sha256 "46682377e788f4f6e4f43abccadb4246d896c275a563d3e3b695a4d07055d412"
      define_method(:install) do
        bin.install "cpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JakubKontra/claude-profile-manager/releases/download/v0.2.0/cpm_linux_arm64"
      sha256 "4fb05090f767e850a58cbfa40621f36a4c0507b9d19eec30c10294a2fa0eb085"
      define_method(:install) do
        bin.install "cpm"
      end
    end
  end

  test do
    system "#{bin}/cpm", "version"
  end
end
